### ISSUE TITLE
End-To-End testing

### ISSUE THREAD

**Issue by rawleyfowler** [rawleyfowler/Humming-Bird#20]
We should probably setup some end-to-end tests!

**Comment by melezhik** [comment]
Just like an idea 💡 you can use SparrowCI for that : nohup cro run & < /dev/null and then run your tests …

**Comment by rawleyfowler** [comment]
@melezhik I added some basic Integration Testing in the Advice branch, I think I will see if they run on SparrowCI tomorrow.
