### ISSUE TITLE
listen doesn't honor port number

### ISSUE THREAD

**Issue by masukomi** [rawleyfowler/Humming-Bird#23]
not sure what's going on yet. but it's always 8080... will update when i know.

**Comment by rawleyfowler** [comment]
Hmm I don't think anyone has tested it without 8080 yet so you're breaking new ground, thanks!

**Comment by rawleyfowler** [comment]
I actually found the culprit, and it's such a silly mistake. I noticed you forked this so if you want to give it a PR, go right ahead! Otherwise I can fix it up real quick for you!

**Comment by masukomi** [comment]
go ahead and fix it. 
I have another refactoring pr planned and you doing that will save me from having to make 2 ;)

**Comment by rawleyfowler** [comment]
Great, excited to see it :D
