### ISSUE TITLE
Add catch-all routes

### ISSUE THREAD

**Issue by rawleyfowler** [rawleyfowler/Humming-Bird#30]
Right now you can't easily add a catch-all route for a given location.

For example it might be nice to do:

```raku
get('/*', ...);
```

So that any route that doesn't fit an already defined location can be caught.

**Comment by masukomi** [comment]
This reminds me of a talk I recently watched about [Roda](https://roda.jeremyevans.net/) (video linked at bottom of Roda home page).

Rhoda wasn't very compelling to me overall (it's an abandoned sinatra competitor in ruby), but I think there's a lot of cool thinking in the routing-tree approach he took. I think the video gives a really nice explanation of it and the benefits that derive from it.

It's atypical, but I'm coming to believe that it's actually better. I'm thinking that as the routing stuff here is so new and unfinished (this plus you wanted to write that grammar) that maybe it'd be a good time to contemplate that approach (before this gets too much traction to make changes like that). 

Anyway, just throwing that out there as it is a solution to this problem, and potentially others.

**Comment by rawleyfowler** [comment]
@masukomi Yeah it is a very neat approach to this!

**Comment by rawleyfowler** [comment]
I'm going to get started on a "MVP 1" pass of this, on the weekend. I think I am going to stick with our current routing, but later (possibly when we introduce grammar/slang based route encoding) we can look into more interesting routing schemes. For now however, I just want to get the feature into production.
