### ISSUE TITLE
Missing single quote in routers example

### ISSUE THREAD

**Issue by hjxkyw** [rawleyfowler/Humming-Bird#62]
$router.get(-> $request, $response { # Register a GET route on the root of the router
        $response.html('\<h1>Hello World\</h1>);
    });

**Comment by rawleyfowler** [comment]
I will gladly take a PR to fix this if you'd like :)

**Comment by hjxkyw** [comment]
Thanks for the reply. Unfortunately I don't do git (will start soon at my workplace).

**Comment by rawleyfowler** [comment]
No worries, I can fix it.

**Comment by hjxkyw** [comment]
👍
