### ISSUE TITLE
multipart/form-data POST body doesn't parse

### ISSUE THREAD

**Issue by swaggboi** [rawleyfowler/Humming-Bird#66]
Hello, trying to figure out how to handle a file upload via multipart/form-data POST body; here is my Humming-Bird code:

    #!/usr/bin/env raku
    
    use v6.d;
    use Humming-Bird::Core;
    use Humming-Bird::Middleware;
    use Humming-Bird::Advice;
    use Template::Mustache;
    
    my $template = Template::Mustache.new: :from<./templates>;
    
    middleware &middleware-logger;
    advice     &advice-logger;
    
    get '/', -> $request, $response {
        my Str %stash = title => 'File upload';
    
        $response.html($template.render: 'index', %stash);
    };
    
    post '/', -> $request, $response {
        dd $request;
    
        $response.redirect('/');
    };
    
    listen 3000;
    
And here is my template/form:

    <!DOCTYPE html>
    <html>
    <head>
      <title>{{title}}</title>
    </head>
    <body>
    <h1>{{title}}</h1>
    <form method="post" enctype="multipart/form-data">
      <div>
        <label for="file-upload">File</label>
        <input type="file" name="file-upload" id="file-upload"
               accept="image/jpeg, image/png, .jpeg, .jpg, .png">
      </div>
      <button type="submit">Upload</button>
    </form>
    </body>
    </html>

When I make the POST in my browser by uploading a small (<100KB) JPEG, I get a TCP reset in the browser and in the text console I get:

    Malformed UTF-8 near bytes 0d 0a ff at line 23 col 1
      in block  at /home/daniel/.raku/sources/000B68E7460EE82EB3F0D7FFB96DAB6C0199C762 (Humming-Bird::HTTPServer) line 43

I get this even if I comment out the `dd $request` line so it seems to not like that POST body. I tried stopping the script after performing the GET to render the form, firing up `nc -l 3000` in a terminal and then completing the form in my browser. The POST request body includes a `Content-Disposition` header and a `Content-Type` header and looks like a well-formed multipart/form-data POST to me:

    POST / HTTP/1.1
    Host: localhost:3000
    User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115
    .0
    Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8
    Accept-Language: en-US,en;q=0.5
    Accept-Encoding: gzip, deflate, br
    Content-Type: multipart/form-data; boundary=---------------------------21740014396030127931917243238
    Content-Length: 31382
    Origin: http://localhost:3000
    DNT: 1
    Connection: keep-alive
    Referer: http://localhost:3000/
    Upgrade-Insecure-Requests: 1
    Sec-Fetch-Dest: document
    Sec-Fetch-Mode: navigate
    Sec-Fetch-Site: same-origin
    Sec-Fetch-User: ?1
    
    -----------------------------21740014396030127931917243238
    Content-Disposition: form-data; name="file-upload"; filename="screenboop.jpg"
    Content-Type: image/jpeg
    
    <binary stuff here...>
    -----------------------------21740014396030127931917243238--

I was hoping I could access the content-type and parameter name attributes in addition to the bytes that comprise the file itself. Would be neat to handle multiple files too using the filename attribute if that's do-able?

**Comment by rawleyfowler** [comment]
@swaggboi This is an oversight in the inferred content parser. Also please update your Humming-Bird to `3.0.0` and re-test, it will give us a better error message to work with.

**Comment by swaggboi** [comment]
@rawleyfowler I'm having trouble getting Humming-Bird::Advice on a couple Debian 12 machines I tried with similar outcome:

    $ zef install -v --force-install https://github.com/rawleyfowler/Humming-Bird.git
    ===> Fetching [OK]: https://github.com/rawleyfowler/Humming-Bird.git to /home/daniel/.zef/tmp/1699500637.1429275.1118.5605163009361/Humming-Bird.git
    ===> Extraction [OK]: https://github.com/rawleyfowler/Humming-Bird.git to /home/daniel/.zef/tmp/Humming-Bird.git
    ===> Testing: Humming-Bird:ver<3.0.0>:auth<zef:rawleyfowler>
    [Humming-Bird] t/01-basic.rakutest .............. ok
    [Humming-Bird] t/02-request_encoding.rakutest ... ok
    [Humming-Bird] t/03-response_decoding.rakutest .. ok
    [Humming-Bird] t/04-middleware.rakutest ......... ok
    [Humming-Bird] t/05-cookie.rakutest ............. ok
    [Humming-Bird] t/06-redirect.rakutest ........... ok
    [Humming-Bird] t/07-advice.rakutest ............. ok
    [Humming-Bird] t/08-static.rakutest ............. ok
    [Humming-Bird] t/09-routers.rakutest ............ ok
    [Humming-Bird] t/10-content-guessing.rakutest ... ok
    [Humming-Bird] t/11-advanced-query.rakutest ..... ok
    [Humming-Bird] t/12-headers.rakutest ............ ok
    [Humming-Bird] All tests successful.
    [Humming-Bird] Files=12, Tests=88,  8 wallclock secs
    [Humming-Bird] Result: PASS
    ===> Testing [OK] for Humming-Bird:ver<3.0.0>:auth<zef:rawleyfowler>
    ===> Installing: Humming-Bird:ver<3.0.0>:auth<zef:rawleyfowler>
    ===> Install [FAIL] for Humming-Bird:ver<3.0.0>:auth<zef:rawleyfowler>: ===SORRY!=== Error while compiling /home/daniel/home#sources/4FB18FDB645F4341AC241AC828C268FBB2F05A39 (Humming-Bird::Advice)
    Invalid typename 'Response' in parameter declaration.
    at /home/daniel/home#sources/4FB18FDB645F4341AC241AC828C268FBB2F05A39 (Humming-Bird::Advice):26
    ------> sub advice-logger(Response:D⏏ $response --> Response:D) is export {
        expecting any of:
            pair value
    
    ===SORRY!=== Error while compiling /home/daniel/home#sources/4FB18FDB645F4341AC241AC828C268FBB2F05A39 (Humming-Bird::Advice)
    Invalid typename 'Response' in parameter declaration.
    at /home/daniel/home#sources/4FB18FDB645F4341AC241AC828C268FBB2F05A39 (Humming-Bird::Advice):26
    ------> sub advice-logger(Response:D⏏ $response --> Response:D) is export {
        expecting any of:
            pair value

**Comment by rawleyfowler** [comment]
@swaggboi Ah shit. `zef install --force-install --force-test` for now. I will fix this along with this bug, and release as `3.0.1` tonight.

**Comment by swaggboi** [comment]
OK sounds good, I ended up installing `rakubrew` to try to work around it... Didn't work but at least I have it now 😅

**Comment by rawleyfowler** [comment]
Yeah that's totally my bad. I missed an import on the default advice module (guess its time to write a test there :P )

**Comment by rawleyfowler** [comment]
@swaggboi  Going to push up some experimental changes to a branch, feel free to pull them down and try them out. (I haven't 100% cased parsing multipart yet, but it shouldn't explode anymore).

**Comment by rawleyfowler** [comment]
https://github.com/rawleyfowler/Humming-Bird/tree/fix-multipart , the tests will fail for now, just force install. I should have an official release to fix this sometime tomorrow.

**Comment by rawleyfowler** [comment]
@swaggboi I've got a release coming out in a few minutes that doesn't fix this unfortunately, but it sets the ground to fix it. Raku really gets in your way when it comes to dealing in binary, and since multipart is half-binary-half-text the encoding is having a stroke.

**Comment by swaggboi** [comment]
@rawleyfowler Thank you sorry last night I got tired fighting `rakubrew` (unrelated to this) and ended up throwing in the towel. The system `raku` works fine so tonight after work I can pivot back to testing this ☢️ 🤪

**Comment by rawleyfowler** [comment]
@swaggboi You should be able to pull `3.0.1` in a few minutes!

**Comment by swaggboi** [comment]
@rawleyfowler I can run this now with no errors (and I'm finally on v3!)

**Comment by rawleyfowler** [comment]
@swaggboi Awesome. Just you wait, I now know wayyyy too much about `multipart/form-data` from today and a file-upload fix is coming!

**Comment by swaggboi** [comment]
@rawleyfowler I owe you a coffee or 12!

**Comment by rawleyfowler** [comment]
@swaggboi This should all be cleaned up in `3.0.2`. Thanks again for the great bug reporting :D

![image](https://github.com/rawleyfowler/Humming-Bird/assets/75388349/95f1b6fe-34c3-4be0-9d7c-e7612cd0f203)
