### ISSUE TITLE
Feature request: reload on source code changes

### ISSUE THREAD

**Issue by melezhik** [rawleyfowler/Humming-Bird#75]
Hi! Is it possible to have an app reload when source code files change?

**Comment by rawleyfowler** [comment]
Currently, it is not possible, I have been thinking about this quite a bit actually, I think the best course of action is to add a new backend.

**Comment by rawleyfowler** [comment]
This is a much bigger undertaking than I thought it would be, especially considering the way Humming-Bird works, I will continue to investigate, however don't expect much until after the new year.

**Comment by rawleyfowler** [comment]
@melezhik This is now completed as of Humming-Bird version `3.0.5`. to use it simply:

```raku
plugin 'HotReload';
```

**Comment by melezhik** [comment]
👍, thanks , will check it out
