### ISSUE TITLE
Feature request: Ability to listen not only on localhost

### ISSUE THREAD

**Issue by melezhik** [rawleyfowler/Humming-Bird#76]
Hi! I wonder if this is possible, I have not found in docs

**Comment by rawleyfowler** [comment]
I can implement this today at some point, should be easy.

**Comment by rawleyfowler** [comment]
Also by default, Humming-Bird listens on `0.0.0.0` anyways so you should be bound to all addresses on the port as is.

**Comment by rawleyfowler** [comment]
@melezhik Please pull latest with:

```
zef install --force-install https://github.com/rawleyfowler/Humming-Bird
```

**Comment by melezhik** [comment]
Thanks!
