### ISSUE TITLE
Feature request: simple configuration using some ( well known ) formats 

### ISSUE THREAD

**Issue by melezhik** [rawleyfowler/Humming-Bird#78]
Hi! Maybe we could have a sort of configuration file placed in a project root, say .hb.toml where a user could place their stuff / configuration variables accessible in humming bird context ? Just an idea.

**Comment by rawleyfowler** [comment]
I am thinking this can be done with a: `config` global function, so you call `config 'foo'` and it will retrieve the `foo` field inside of your `hb.json`

**Comment by melezhik** [comment]
Cool! I did not see hb.json is mentioned in the docs, do you consider supporting others formats like toml ? Or this 
will contradict the idea of hb being lightweight ?

**Comment by rawleyfowler** [comment]
@melezhik This is currently not implemented, I think you may be referring to HummingBird (the swift web framework lol)

**Comment by rawleyfowler** [comment]
@melezhik This will be implemented later today alongside a plugin system!

**Comment by melezhik** [comment]
Cool! I am going to test it soon. I use your web framework on my work
