### ISSUE TITLE
SparkyCI build fails

### ISSUE THREAD

**Issue by melezhik** [rawleyfowler/Humming-Bird#82]
Hi! I've migrated the pipeline to Sparky and now build fails - https://sparky.sparrowhub.io/report/gh-rawleyfowler-Humming-Bird/22420

19:34:42 :: ===> Testing [OK] for Test::Util::ServerPort:ver<0.0.5>:auth<zef:jonathanstowe>:api<1.0>
19:34:42 :: ===> Testing: IO::Socket::Async::SSL:ver<0.7.14>:auth<zef:jnthn>
19:34:42 :: [IO::Socket::Async::SSL] # address already in use
19:34:42 :: ===> Testing [FAIL]: IO::Socket::Async::SSL:ver<0.7.14>:auth<zef:jnthn>

I guess this is IO::Socket::Async::SSL fault 

HTH, Alexey

If you want to change the pipeline - please do so via PR - https://github.com/melezhik/ci.sparrowhub/blob/master/projects/gh-rawleyfowler-Humming-Bird/sparrowfile

**Comment by rawleyfowler** [comment]
I'm guessing that's just an issue with the container not having `OpenSSL` installed.

**Comment by melezhik** [comment]
I've added SSL info, please take a look - https://sparky.sparrowhub.io/report/gh-rawleyfowler-Humming-Bird/22432 
artifacts->ssl.txt

**Comment by melezhik** [comment]
it passed now btw, looks like flickering bug with IO::Socket::Async::SSL passing it's tests

**Comment by rawleyfowler** [comment]
Cool, thanks!
