### ISSUE TITLE
Does not install in Windows 11 because of Crypt::Random

### ISSUE THREAD

**Issue by hjxkyw** [rawleyfowler/Humming-Bird#83]
Hi

Thanks for your work.

Unfortunately this module does not install in Windows 11, because zef fails to install the Crypt::Random dependency.
I looked at the code for Crypt::Random, and it's **very** old, and it seems it's not maintained anymore.

Windows build: 22000.2538

$ raku --version
Welcome to Rakudo™ v2024.09.
Implementing the Raku® Programming Language v6.d.
Built on MoarVM version 2024.09.

$ zef --version
0.22.2

I don't really need this module, but it would be cool to play with it.

Regards

**Comment by rawleyfowler** [comment]
Crypt::Random is required by UUID::v4 (which Humming-Bird uses). It is said to work on Windows as well. 

Can you please post an error log, thanks.

**Comment by hjxkyw** [comment]
Hi

Thanks for your reply.

Below is the output of "zef install Crypt::Random.

[zef_output.txt](https://github.com/user-attachments/files/17367504/zef_output.txt)

**Comment by rawleyfowler** [comment]
Just use `zef install --force-test Crypt::Random` for now. That module and it's parent aren't used in any Core Humming-Bird features, unless you use sessions.

**Comment by hjxkyw** [comment]
Hi

There was an error in JSON::Unmarshal, then I installed with --force-test.
Other errors showed up, in the end I installed Humming-Bird:::Core with --force-test also.

It's passing the "hello world" test.
For me that's good at the moment.

Thanks for the attention

**Comment by rawleyfowler** [comment]
No worries. Humming-Bird is only tested for Linux and MacOS, so there may be issues running on Windows. We usually accept patches for Windows however, so if you find any issues open another one on GitHub. Thanks!
